=== raml-apis/Meetup/schemas/deprecated-checkin-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "checker": {
      "required": false,
      "type": "object",
      "properties": {
        "member_city": {
          "required": false,
          "type": "string"
        },
        "member_country": {
          "required": false,
          "type": "string"
        },
        "member_id": {
          "required": false,
          "type": "integer"
        },
        "member_state": {
          "required": false,
          "type": "string"
        },
        "name": {
          "required": false,
          "type": "string"
        }
      }
    },
    "checkin_id": {
      "required": false,
      "type": "integer"
    },
    "comment": {
      "required": false,
      "type": "string"
    },
    "event_id": {
      "required": false,
      "type": "integer"
    },
    "group_id": {
      "required": false,
      "type": "integer"
    },
    "lat": {
      "required": false,
      "type": "number"
    },
    "lon": {
      "required": false,
      "type": "number"
    },
    "member_id": {
      "required": false,
      "type": "integer"
    },
    "member_name": {
      "required": false,
      "type": "string"
    },
    "time": {
      "required": false,
      "type": "integer"
    }
  }
}

=== raml-apis/Meetup/examples/deprecated-checkin.json
{
  "checkin_id": 100,
  "time": 100,
  "lon": 1.0,
  "group_id": 100,
  "event_id": 100,
  "member_name": "member_name",
  "comment": "comment",
  "lat": 1.0,
  "checker": {
    "member_state": "member_state",
    "member_city": "member_city",
    "name": "name",
    "member_country": "member_country",
    "member_id": 100
  },
  "member_id": 100
}
