=== raml-apis/Meetup/schemas/discussion-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "body": {
      "required": false,
      "type": "string"
    },
    "created": {
      "required": false,
      "type": "integer"
    },
    "discussion": {
      "required": false,
      "type": "object",
      "properties": {
        "id": {
          "required": false,
          "type": "integer"
        }
      }
    },
    "id": {
      "required": false,
      "type": "integer"
    },
    "in_reply_to": {
      "required": false,
      "type": "integer"
    },
    "member": {
      "required": false,
      "type": "object",
      "properties": {
        "city": {
          "required": false,
          "type": "string"
        },
        "country": {
          "required": false,
          "type": "string"
        },
        "id": {
          "required": false,
          "type": "integer"
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "photo": {
          "required": false,
          "type": "object",
          "properties": {
            "thumb": {
              "required": false,
              "type": "integer"
            }
          }
        },
        "state": {
          "required": false,
          "type": "integer"
        }
      }
    },
    "subject": {
      "required": false,
      "type": "string"
    },
    "updated": {
      "required": false,
      "type": "integer"
    }
  }
}

=== raml-apis/Meetup/examples/discussion.json
{
  "member": {
    "id": 100,
    "name": "name",
    "state": 100,
    "photo": {
      "thumb": 100
    },
    "country": "country",
    "city": "city"
  },
  "id": 100,
  "body": "body",
  "discussion": {
    "id": 100
  },
  "updated": 100,
  "created": 100,
  "subject": "subject",
  "in_reply_to": 100
}
