=== raml-apis/Meetup/schemas/event-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "announced": {
      "required": false,
      "type": "string"
    },
    "comment_count": {
      "required": false,
      "type": "integer"
    },
    "created": {
      "required": false,
      "type": "integer"
    },
    "description": {
      "required": false,
      "type": "string"
    },
    "distance": {
      "required": false,
      "type": "number"
    },
    "duration": {
      "required": false,
      "type": "integer"
    },
    "email_reminders": {
      "required": false,
      "type": "string"
    },
    "event_hosts": {
      "required": false,
      "type": "object",
      "properties": {
        "member_id": {
          "required": false,
          "type": "integer"
        },
        "member_name": {
          "required": false,
          "type": "string"
        }
      }
    },
    "event_url": {
      "required": false,
      "type": "string"
    },
    "featured": {
      "required": false,
      "type": "string"
    },
    "fee": {
      "required": false,
      "type": "object",
      "properties": {
        "accepts": {
          "required": false,
          "type": "string"
        },
        "amount": {
          "required": false,
          "type": "string"
        },
        "currency": {
          "required": false,
          "type": "string"
        },
        "description": {
          "required": false,
          "type": "string"
        },
        "label": {
          "required": false,
          "type": "integer"
        },
        "required": {
          "required": false,
          "type": "string"
        }
      }
    },
    "group": {
      "required": false,
      "type": "object",
      "properties": {
        "category": {
          "required": false,
          "type": "object",
          "properties": {
            "id": {
              "required": false,
              "type": "integer"
            },
            "name": {
              "required": false,
              "type": "string"
            },
            "shortname": {
              "required": false,
              "type": "string"
            }
          }
        },
        "group_lat": {
          "required": false,
          "type": "string"
        },
        "group_lon": {
          "required": false,
          "type": "string"
        },
        "group_photo": {
          "required": false,
          "type": "object",
          "properties": {
            "highres_link": {
              "required": false,
              "type": "string"
            },
            "photo_id": {
              "required": false,
              "type": "integer"
            },
            "photo_link": {
              "required": false,
              "type": "string"
            },
            "thumb_link": {
              "required": false,
              "type": "string"
            }
          }
        },
        "id": {
          "required": false,
          "type": "integer"
        },
        "join_mode": {
          "required": false,
          "type": "string"
        },
        "membership_dues": {
          "required": false,
          "type": "object",
          "properties": {
            "currency": {
              "required": false,
              "type": "string"
            },
            "fee": {
              "required": false,
              "type": "string"
            },
            "fee_desc": {
              "required": false,
              "type": "string"
            },
            "methods": {
              "required": false,
              "type": "string"
            },
            "refund_policy": {
              "required": false,
              "type": "string"
            },
            "required": {
              "required": false,
              "type": "string"
            }
          }
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "topics": {
          "required": false,
          "type": "object",
          "properties": {
            "id": {
              "required": false,
              "type": "integer"
            },
            "name": {
              "required": false,
              "type": "string"
            },
            "urlkey": {
              "required": false,
              "type": "string"
            }
          }
        },
        "urlname": {
          "required": false,
          "type": "string"
        },
        "who": {
          "required": false,
          "type": "string"
        }
      }
    },
    "headcount": {
      "required": false,
      "type": "string"
    },
    "how_to_find_us": {
      "required": false,
      "type": "string"
    },
    "id": {
      "required": false,
      "type": "integer"
    },
    "is_simplehtml": {
      "required": false,
      "type": "string"
    },
    "maybe_rsvp_count": {
      "required": false,
      "type": "integer"
    },
    "name": {
      "required": false,
      "type": "string"
    },
    "photo_album_id": {
      "required": false,
      "type": "integer"
    },
    "photo_count": {
      "required": false,
      "type": "integer"
    },
    "photo_url": {
      "required": false,
      "type": "string"
    },
    "publish_status": {
      "required": false,
      "type": "string"
    },
    "rating": {
      "required": false,
      "type": "object",
      "properties": {
        "average": {
          "required": false,
          "type": "string"
        },
        "count": {
          "required": false,
          "type": "integer"
        }
      }
    },
    "rsvp_alerts": {
      "required": false,
      "type": "string"
    },
    "rsvp_limit": {
      "required": false,
      "type": "string"
    },
    "rsvp_rules": {
      "required": false,
      "type": "object",
      "properties": {
        "close_time": {
          "required": false,
          "type": "string"
        },
        "closed": {
          "required": false,
          "type": "string"
        },
        "guest_limit": {
          "required": false,
          "type": "string"
        },
        "open_time": {
          "required": false,
          "type": "string"
        },
        "refund_policy": {
          "required": false,
          "type": "object",
          "properties": {
            "days": {
              "required": false,
              "type": "string"
            },
            "notes": {
              "required": false,
              "type": "integer"
            },
            "policies": {
              "required": false,
              "type": "string"
            }
          }
        },
        "waitlisting": {
          "required": false,
          "type": "string"
        }
      }
    },
    "rsvpable": {
      "required": false,
      "type": "string"
    },
    "self": {
      "required": false,
      "type": "object",
      "properties": {
        "actions": {
          "required": false,
          "type": "string"
        },
        "checked_in": {
          "required": false,
          "type": "string"
        },
        "pay_status": {
          "required": false,
          "type": "string"
        },
        "rated": {
          "required": false,
          "type": "integer"
        },
        "role": {
          "required": false,
          "type": "string"
        },
        "rsvp": {
          "required": false,
          "type": "object",
          "properties": {
            "answers": {
              "required": false,
              "type": "string"
            },
            "guests": {
              "required": false,
              "type": "string"
            },
            "response": {
              "required": false,
              "type": "string"
            }
          }
        },
        "watching": {
          "required": false,
          "type": "string"
        }
      }
    },
    "short_link": {
      "required": false,
      "type": "string"
    },
    "simple_html_description": {
      "required": false,
      "type": "string"
    },
    "status": {
      "required": false,
      "type": "string"
    },
    "survey_questions": {
      "required": false,
      "type": "object",
      "properties": {
        "id": {
          "required": false,
          "type": "integer"
        },
        "question": {
          "required": false,
          "type": "string"
        },
        "required": {
          "required": false,
          "type": "string"
        }
      }
    },
    "time": {
      "required": false,
      "type": "integer"
    },
    "timezone": {
      "required": false,
      "type": "string"
    },
    "trending_rank": {
      "required": false,
      "type": "string"
    },
    "updated": {
      "required": false,
      "type": "integer"
    },
    "utc_offset": {
      "required": false,
      "type": "integer"
    },
    "venue": {
      "required": false,
      "type": "object",
      "properties": {
        "address_1": {
          "required": false,
          "type": "string"
        },
        "address_2": {
          "required": false,
          "type": "string"
        },
        "address_3": {
          "required": false,
          "type": "string"
        },
        "city": {
          "required": false,
          "type": "string"
        },
        "state": {
          "required": false,
          "type": "integer"
        },
        "country": {
          "required": false,
          "type": "string"
        },
        "id": {
          "required": false,
          "type": "integer"
        },
        "lat": {
          "required": false,
          "type": "number"
        },
        "lon": {
          "required": false,
          "type": "number"
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "phone": {
          "required": false,
          "type": "integer"
        },
        "repinned": {
          "required": false,
          "type": "string"
        },
        "zip": {
          "required": false,
          "type": "string"
        }
      }
    },
    "venue_visibility": {
      "required": false,
      "type": "string"
    },
    "visibility": {
      "required": false,
      "type": "string"
    },
    "why": {
      "required": false,
      "type": "string"
    },
    "yes_rsvp_count": {
      "required": false,
      "type": "integer"
    }
  }
}

=== raml-apis/Meetup/examples/event.json
{
  "visibility": "visibility",
  "is_simplehtml": "is_simplehtml",
  "self": {
    "checked_in": "checked_in",
    "watching": "watching",
    "rsvp": {
      "response": "response",
      "guests": "guests",
      "answers": "answers"
    },
    "role": "role",
    "rated": 100,
    "actions": "actions",
    "pay_status": "pay_status"
  },
  "featured": "featured",
  "rsvpable": "rsvpable",
  "publish_status": "publish_status",
  "email_reminders": "email_reminders",
  "rsvp_rules": {
    "open_time": "open_time",
    "waitlisting": "waitlisting",
    "close_time": "close_time",
    "guest_limit": "guest_limit",
    "closed": "closed",
    "refund_policy": {
      "days": "days",
      "notes": 100,
      "policies": "policies"
    }
  },
  "id": 100,
  "timezone": "timezone",
  "time": 100,
  "distance": 1.0,
  "venue_visibility": "venue_visibility",
  "yes_rsvp_count": 100,
  "updated": 100,
  "created": 100,
  "description": "description",
  "survey_questions": {
    "id": 100,
    "question": "question",
    "required": "required"
  },
  "headcount": "headcount",
  "name": "name",
  "photo_album_id": 100,
  "rsvp_alerts": "rsvp_alerts",
  "photo_count": 100,
  "comment_count": 100,
  "rsvp_limit": "rsvp_limit",
  "trending_rank": "trending_rank",
  "status": "status",
  "maybe_rsvp_count": 100,
  "photo_url": "photo_url",
  "venue": {
    "id": 100,
    "zip": "zip",
    "phone": 100,
    "lon": 1.0,
    "repinned": "repinned",
    "address_3": "address_3",
    "name": "name",
    "state": 100,
    "address_1": "address_1",
    "address_2": "address_2",
    "lat": 1.0,
    "country": "country",
    "city": "city"
  },
  "short_link": "short_link",
  "event_hosts": {
    "member_name": "member_name",
    "member_id": 100
  },
  "utc_offset": 100,
  "fee": {
    "amount": "amount",
    "description": "description",
    "label": 100,
    "required": "required",
    "accepts": "accepts",
    "currency": "currency"
  },
  "duration": 100,
  "announced": "announced",
  "event_url": "event_url",
  "how_to_find_us": "how_to_find_us",
  "rating": {
    "count": 100,
    "average": "average"
  },
  "group": {
    "id": 100,
    "topics": {
      "id": 100,
      "urlkey": "urlkey",
      "name": "name"
    },
    "category": {
      "id": 100,
      "name": "name",
      "shortname": "shortname"
    },
    "group_photo": {
      "photo_link": "photo_link",
      "highres_link": "highres_link",
      "thumb_link": "thumb_link",
      "photo_id": 100
    },
    "group_lat": "group_lat",
    "name": "name",
    "group_lon": "group_lon",
    "membership_dues": {
      "methods": "methods",
      "fee": "fee",
      "required": "required",
      "fee_desc": "fee_desc",
      "refund_policy": "refund_policy",
      "currency": "currency"
    },
    "join_mode": "join_mode",
    "urlname": "urlname",
    "who": "who"
  },
  "simple_html_description": "simple_html_description",
  "why": "why"
}
