=== raml-apis/Meetup/schemas/everywhere-rsvp-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "created": {
      "required": false,
      "type": "integer"
    },
    "event_id": {
      "required": false,
      "type": "integer"
    },
    "id": {
      "required": false,
      "type": "integer"
    },
    "member": {
      "required": false,
      "type": "object",
      "properties": {
        "member_city": {
          "required": false,
          "type": "string"
        },
        "member_country": {
          "required": false,
          "type": "string"
        },
        "member_id": {
          "required": false,
          "type": "integer"
        },
        "member_state": {
          "required": false,
          "type": "string"
        },
        "name": {
          "required": false,
          "type": "string"
        }
      }
    },
    "member_photo": {
      "required": false,
      "type": "object",
      "properties": {
        "highres_link": {
          "required": false,
          "type": "string"
        },
        "photo_id": {
          "required": false,
          "type": "integer"
        },
        "photo_link": {
          "required": false,
          "type": "string"
        },
        "thumb_link": {
          "required": false,
          "type": "string"
        }
      }
    },
    "udf_{varname}": {
      "required": false,
      "type": "string"
    }
  }
}

=== raml-apis/Meetup/examples/everywhere-rsvp.json
{
  "member": {
    "member_state": "member_state",
    "member_city": "member_city",
    "name": "name",
    "member_country": "member_country",
    "member_id": 100
  },
  "id": 100,
  "member_photo": {
    "photo_link": "photo_link",
    "highres_link": "highres_link",
    "thumb_link": "thumb_link",
    "photo_id": 100
  },
  "udf_{varname}": "udf_{varname}",
  "created": 100,
  "event_id": 100
}
