=== raml-apis/Meetup/schemas/everywhere-container-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "countries": {
      "required": false,
      "type": "string"
    },
    "created": {
      "required": false,
      "type": "integer"
    },
    "description": {
      "required": false,
      "type": "string"
    },
    "facebook_urlname": {
      "required": false,
      "type": "string"
    },
    "founder": {
      "required": false,
      "type": "object",
      "properties": {
        "member_city": {
          "required": false,
          "type": "string"
        },
        "member_country": {
          "required": false,
          "type": "string"
        },
        "member_id": {
          "required": false,
          "type": "integer"
        },
        "member_state": {
          "required": false,
          "type": "string"
        },
        "name": {
          "required": false,
          "type": "string"
        }
      }
    },
    "id": {
      "required": false,
      "type": "integer"
    },
    "link": {
      "required": false,
      "type": "string"
    },
    "link_name": {
      "required": false,
      "type": "string"
    },
    "meetup_count": {
      "required": false,
      "type": "integer"
    },
    "meetup_url": {
      "required": false,
      "type": "string"
    },
    "member_count": {
      "required": false,
      "type": "integer"
    },
    "name": {
      "required": false,
      "type": "string"
    },
    "past_meetup_count": {
      "required": false,
      "type": "integer"
    },
    "theme": {
      "required": false,
      "type": "object",
      "properties": {
        "banner_height": {
          "required": false,
          "type": "string"
        },
        "banner_link": {
          "required": false,
          "type": "string"
        },
        "boxback_color": {
          "required": false,
          "type": "string"
        },
        "button_color": {
          "required": false,
          "type": "string"
        },
        "link_color": {
          "required": false,
          "type": "string"
        },
        "pageback_color": {
          "required": false,
          "type": "string"
        }
      }
    },
    "twitter_urlname": {
      "required": false,
      "type": "string"
    },
    "udf_{varname}": {
      "required": false,
      "type": "string"
    },
    "updated": {
      "required": false,
      "type": "integer"
    },
    "urlname": {
      "required": false,
      "type": "string"
    }
  }
}

=== raml-apis/Meetup/examples/everywhere-container.json
{
  "twitter_urlname": "twitter_urlname",
  "member_count": 100,
  "link_name": "link_name",
  "meetup_count": 100,
  "theme": {
    "pageback_color": "pageback_color",
    "link_color": "link_color",
    "banner_height": "banner_height",
    "button_color": "button_color",
    "boxback_color": "boxback_color",
    "banner_link": "banner_link"
  },
  "link": "link",
  "past_meetup_count": 100,
  "countries": "countries",
  "facebook_urlname": "facebook_urlname",
  "id": 100,
  "updated": 100,
  "udf_{varname}": "udf_{varname}",
  "created": 100,
  "description": "description",
  "name": "name",
  "meetup_url": "meetup_url",
  "urlname": "urlname",
  "founder": {
    "member_state": "member_state",
    "member_city": "member_city",
    "name": "name",
    "member_country": "member_country",
    "member_id": 100
  }
}
