=== raml-apis/Meetup/schemas/group-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "category": {
      "required": false,
      "type": "object",
      "properties": {
        "id": {
          "required": false,
          "type": "integer"
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "shortname": {
          "required": false,
          "type": "string"
        }
      }
    },
    "city": {
      "required": false,
      "type": "string"
    },
    "country": {
      "required": false,
      "type": "string"
    },
    "created": {
      "required": false,
      "type": "integer"
    },
    "description": {
      "required": false,
      "type": "string"
    },
    "ga_code": {
      "required": false,
      "type": "string"
    },
    "group_photo": {
      "required": false,
      "type": "object",
      "properties": {
        "highres_link": {
          "required": false,
          "type": "string"
        },
        "id": {
          "required": false,
          "type": "integer"
        },
        "photo_link": {
          "required": false,
          "type": "string"
        },
        "thumb_link": {
          "required": false,
          "type": "string"
        }
      }
    },
    "id": {
      "required": false,
      "type": "integer"
    },
    "is_simplehtml": {
      "required": false,
      "type": "string"
    },
    "join_info": {
      "required": false,
      "type": "object",
      "properties": {
        "intro_required": {
          "required": false,
          "type": "string"
        },
        "photo_required": {
          "required": false,
          "type": "string"
        },
        "questions": {
          "required": false,
          "type": "object",
          "properties": {
            "id": {
              "required": false,
              "type": "integer"
            },
            "question": {
              "required": false,
              "type": "string"
            }
          }
        },
        "questions_req": {
          "required": false,
          "type": "string"
        }
      }
    },
    "join_mode": {
      "required": false,
      "type": "string"
    },
    "lat": {
      "required": false,
      "type": "number"
    },
    "link": {
      "required": false,
      "type": "string"
    },
    "list_addr": {
      "required": false,
      "type": "string"
    },
    "list_mode": {
      "required": false,
      "type": "string"
    },
    "lon": {
      "required": false,
      "type": "number"
    },
    "members": {
      "required": false,
      "type": "string"
    },
    "name": {
      "required": false,
      "type": "string"
    },
    "next_event": {
      "required": false,
      "type": "object",
      "properties": {
        "id": {
          "required": false,
          "type": "integer"
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "time": {
          "required": false,
          "type": "integer"
        }
      }
    },
    "organizer": {
      "required": false,
      "type": "object",
      "properties": {
        "bio": {
          "required": false,
          "type": "string"
        },
        "id": {
          "required": false,
          "type": "integer"
        },
        "name": {
          "required": false,
          "type": "string"
        }
      }
    },
    "photos": {
      "required": false,
      "type": "object",
      "properties": {
        "highres_link": {
          "required": false,
          "type": "string"
        },
        "id": {
          "required": false,
          "type": "integer"
        },
        "photo_link": {
          "required": false,
          "type": "string"
        },
        "thumb_link": {
          "required": false,
          "type": "string"
        }
      }
    },
    "simple_html_description": {
      "required": false,
      "type": "string"
    },
    "state": {
      "required": false,
      "type": "integer"
    },
    "timezone": {
      "required": false,
      "type": "string"
    },
    "urlname": {
      "required": false,
      "type": "string"
    },
    "visibility": {
      "required": false,
      "type": "string"
    },
    "who": {
      "required": false,
      "type": "string"
    }
  }
}

=== raml-apis/Meetup/examples/group.json
{
  "visibility": "visibility",
  "is_simplehtml": "is_simplehtml",
  "link": "link",
  "next_event": {
    "id": 100,
    "time": 100,
    "name": "name"
  },
  "state": 100,
  "join_mode": "join_mode",
  "who": "who",
  "city": "city",
  "id": 100,
  "timezone": "timezone",
  "created": 100,
  "list_addr": "list_addr",
  "description": "description",
  "ga_code": "ga_code",
  "name": "name",
  "urlname": "urlname",
  "lat": 1.0,
  "members": "members",
  "list_mode": "list_mode",
  "lon": 1.0,
  "join_info": {
    "questions": {
      "id": 100,
      "question": "question"
    },
    "intro_required": "intro_required",
    "questions_req": "questions_req",
    "photo_required": "photo_required"
  },
  "organizer": {
    "id": 100,
    "bio": "bio",
    "name": "name"
  },
  "country": "country",
  "photos": {
    "id": 100,
    "photo_link": "photo_link",
    "highres_link": "highres_link",
    "thumb_link": "thumb_link"
  },
  "category": {
    "id": 100,
    "name": "name",
    "shortname": "shortname"
  },
  "group_photo": {
    "id": 100,
    "photo_link": "photo_link",
    "highres_link": "highres_link",
    "thumb_link": "thumb_link"
  },
  "simple_html_description": "simple_html_description"
}
