=== raml-apis/Meetup/schemas/member-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "type": "object",
  "properties": {
    "bio": {
      "required": false,
      "type": "string"
    },
    "birthday": {
      "required": false,
      "type": "object",
      "properties": {
        "day": {
          "required": false,
          "type": "string"
        },
        "month": {
          "required": false,
          "type": "integer"
        },
        "year": {
          "required": false,
          "type": "string"
        }
      }
    },
    "country": {
      "required": false,
      "type": "string"
    },
    "city": {
      "required": false,
      "type": "string"
    },
    "state": {
      "required": false,
      "type": "integer"
    },
    "email": {
      "required": false,
      "type": "integer"
    },
    "gender": {
      "required": false,
      "type": "string"
    },
    "hometown": {
      "required": false,
      "type": "string"
    },
    "id": {
      "required": false,
      "type": "integer"
    },
    "joined": {
      "required": false,
      "type": "integer"
    },
    "lang": {
      "required": false,
      "type": "string"
    },
    "lat": {
      "required": false,
      "type": "number"
    },
    "lon": {
      "required": false,
      "type": "number"
    },
    "link": {
      "required": false,
      "type": "string"
    },
    "membership_count": {
      "required": false,
      "type": "integer"
    },
    "messagable": {
      "required": false,
      "type": "string"
    },
    "messaging_pref": {
      "required": false,
      "type": "string"
    },
    "name": {
      "required": false,
      "type": "string"
    },
    "other_services": {
      "required": false,
      "type": "object",
      "properties": {
        "[service-name]": {
          "required": false,
          "type": "object",
          "properties": {
            "identifier": {
              "required": false,
              "type": "string"
            }
          }
        }
      }
    },
    "photo": {
      "required": false,
      "type": "object",
      "properties": {
        "highres_link": {
          "required": false,
          "type": "string"
        },
        "photo_id": {
          "required": false,
          "type": "integer"
        },
        "photo_link": {
          "required": false,
          "type": "string"
        },
        "thumb_link": {
          "required": false,
          "type": "string"
        }
      }
    },
    "photo_url": {
      "required": false,
      "type": "string"
    },
    "photos": {
      "required": false,
      "type": "string"
    },
    "privacy": {
      "required": false,
      "type": "object",
      "properties": {
        "bio": {
          "required": false,
          "type": "string"
        },
        "facebook": {
          "required": false,
          "type": "string"
        },
        "groups": {
          "required": false,
          "type": "string"
        },
        "photos": {
          "required": false,
          "type": "string"
        },
        "topics": {
          "required": false,
          "type": "string"
        }
      }
    },
    "reachable": {
      "required": false,
      "type": "string"
    },
    "self": {
      "required": false,
      "type": "object",
      "properties": {
        "common": {
          "required": false,
          "type": "object",
          "properties": {
            "friends": {
              "required": false,
              "type": "string"
            },
            "groups": {
              "required": false,
              "type": "string"
            }
          }
        }
      }
    },
    "topics": {
      "required": false,
      "type": "object",
      "properties": {
        "id": {
          "required": false,
          "type": "integer"
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "urlkey": {
          "required": false,
          "type": "string"
        }
      }
    },
    "visited": {
      "required": false,
      "type": "integer"
    }
  }
}

=== raml-apis/Meetup/examples/member.json
{
  "birthday": {
    "month": 100,
    "year": "year",
    "day": "day"
  },
  "messaging_pref": "messaging_pref",
  "link": "link",
  "state": 100,
  "self": {
    "common": {
      "friends": "friends",
      "groups": "groups"
    }
  },
  "lang": "lang",
  "city": "city",
  "visited": 100,
  "id": 100,
  "joined": 100,
  "reachable": "reachable",
  "name": "name",
  "gender": "gender",
  "other_services": {
    "[service-name]": {
      "identifier": "identifier"
    }
  },
  "lat": 1.0,
  "lon": 1.0,
  "hometown": "hometown",
  "membership_count": 100,
  "photo_url": "photo_url",
  "privacy": {
    "photos": "photos",
    "topics": "topics",
    "bio": "bio",
    "facebook": "facebook",
    "groups": "groups"
  },
  "photo": {
    "photo_link": "photo_link",
    "highres_link": "highres_link",
    "thumb_link": "thumb_link",
    "photo_id": 100
  },
  "country": "country",
  "photos": "photos",
  "topics": {
    "id": 100,
    "urlkey": "urlkey",
    "name": "name"
  },
  "bio": "bio",
  "email": 100,
  "messagable": "messagable"
}
